sudo: false
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"

before_install:
  - pip install codecov

install:
  - pip install .
  - pip install -r ./requirements.txt

before_script: flake8 ./etao/

script: nose2 --with-coverage --coverage etao/

after_success:
  - codecov
